site_name: eBioDiv
site_description: Literature services for BioDiversity
site_url: https://bitem-heg-geneve.github.io/ebiodiv-website
repo_url: https://github.com/bitem-heg-geneve/ebiodiv-website
nav:
  - eBioDiv: 'index.md'
  - Documentation: 
      - 'Introduction': 'documentation/index.md'
      - 'Matching algorithm': 'documentation/matching_algorithm.md'
      - 'Data source': 'documentation/data.md'
      - 'Occurrence list': 'documentation/occurrence_list.md'
  - Matching service: https://prod.ebiodiv.org/
  - Sandbox: https://sandbox.ebiodiv.org/
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - abbr
  - tables
  - footnotes
  - def_list
  - pymdownx.critic
theme:
  name: material
  custom_dir: overrides
  locale: en
  include_sidebar: false
  logo: assets/logo_ebiodiv_white.png
  favicon: assets/ebiodiv.ico
  font: false
  palette:
    primary: green
    accent: indigo
  features:
    - navigation.tabs
extra_css:
  - stylesheets/extra.css
plugins:
  - rss:
  - git-revision-date-localized:
      enable_creation_date: true
